const GeneralActionTypes = {
  TOGGLE_IS_LOGIN: "TOGGLE_IS_LOGIN",
  SET_IS_LOGIN: "SET_IS_LOGIN",
  SWITCH_BUTTON: "SWITCH_BUTTON",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  SELECT_TYPE: "SELECT_TYPE",
  SELECT_PIECHART: "SELECT_PIECHART",
  TOGGLE_FORGOT_PASSWORD: "TOGGLE_FORGOT_PASSWORD",
};

export default GeneralActionTypes;
